# Generated by Django 3.2 on 2021-06-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_ordermodel_delivery_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='RestaurentModel',
        ),
    ]
