# Generated by Django 3.2 on 2021-06-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0006_rename_categorymodel_restaurentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurentmodel',
            name='items',
            field=models.ManyToManyField(blank=True, to='shoppingapp.ItemModel'),
        ),
    ]
