# Generated by Django 3.2.4 on 2021-06-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0007_alter_restaurentmodel_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurentmodel',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
