# Generated by Django 3.2.4 on 2021-06-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0008_auto_20210602_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodemodel',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='promocodemodel',
            name='promo',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
